# text_sensor:
#   # Determine the IP Address of the wESP32 and Expose to HA
#   - platform: ethernet_info
#     ip_address:
#       name: Ethernet IP Address
#       entity_category: diagnostic
#   # Determine the Device ID (Mac Address) of the wESP32 and Expose to HA
#   - platform: template
#     name: Device ID
#     id: device_id
#     entity_category: diagnostic
#     update_interval: never
    
sensor:
  # Expose the Board Uptime to HA
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    entity_category: diagnostic
    update_interval: 300s

script:
  - id: update_fault_buzzer
    then:
      - if:
          condition:
            lambda: |-
              return id(Fuse12V).state || id(Fuse3V).state;
          then:
            - switch.turn_on: buzzer
          else:
            - switch.turn_off: buzzer

binary_sensor:
  # - platform: status
  #   name: Status

  # Start +12V Fuse Monitoring - On Fuse Blown, Enable Piezo Buzzer
  - platform: gpio
    id: Fuse12V
    name: 12V Fuse Status
    icon: mdi:fuse
    pin:
      number: GPIO34
      mode:
        input: true
        pullup: false
      inverted: false
    device_class: problem
    on_state:
      - script.execute: update_fault_buzzer
    filters:
        - delayed_on_off: $sensor_debounce_time

  # Start +3.3V Fuse Monitoring - On Fuse Blown, Enable Piezo Buzzer
  - platform: gpio
    id: Fuse3V
    name: 3.3V Fuse Status
    icon: mdi:fuse
    pin:
      number: GPIO36
      mode:
        input: true
        pullup: false
      inverted: true
    device_class: problem
    on_state:
      - script.execute: update_fault_buzzer
    filters:
        - delayed_on_off: $sensor_debounce_time

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
